# collection of all global variables

BLACK_KEYS = []
WHITE_KEYS = []
KEY_TYPE_BLACK = 0
KEY_TYPE_WHITE = 1

WINDOW_X = 10
WINDOW_Y = 10
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 700

DISTANCE_TO_LEFT_MARGIN = 100